### ISSUE TITLE
Track selected on TimeSlot by User

### ISSUE THREAD

**Issue by JFleming4** [JFleming4/FourthYearProjectSite#68]
When a user selects an available time, make sure that selection is tracked for that user. Discussion, Should the availability be similar to the current system in that we students select available times as a group or individually? @DerekStride  @justinkrol  @noahsegal

**Comment by justinkrol** [comment]
Given that we model time slots on the project itself, **let's just make students select times as a group**.
I think that's much simpler.

If we were to do it individually, we'd have to change the model to reflect that, and it would add the following complexity:
- If we're picking unavailable slots, then we should do a union of unavailable times and block those off for the group.
- If we're picking available slots, then we should do an intersection of the available times of all group members and keep the intersection as the group's available times.
