### ISSUE TITLE
Weekly Scrum - [April 1st]

### ISSUE THREAD

**Issue by DerekStride** [JFleming4/FourthYearProjectSite#71]
# Questions
- what have I done last week?
- what will I do this week?
- what is holding me back? (optional)

**Comment by DerekStride** [comment]
**what have I done last week?**
- Opened a PR to update the UIs #69 
- Opened a PR to fix file collision bug #70

**what will I do this week?**
- Fix URL structure
- merge open PRs

**what is holding me back? (optional)**
- I need code reviews on #69 and #70
- I need #48 merged before I can properly set up the URL structure

**Comment by JFleming4** [comment]
#### **what have I done last week?**
- got the basic presentation picker page up
#### **what will I do this week**
- Add the many to many relationship between TimeSlots and users
- Only allow Project supervisor to make TimeSlots
- Select the time slot everyone is available in
#### **what is holding me back**
- I need #48 merged for the relationship between authenticatedUsers and Professors/Students/Coordinators to finish the presentation picker

**Comment by justinkrol** [comment]
#### **What have I done last week?**
- Added errors to the registration and login pages
#### **What will I do this week**
- Adding students to projects
- Creating students or profs with the coordinator
#### **What is holding me back**
Need reviews on #48

**Comment by noahsegal** [comment]
**what have I done last week?**
- Started work on Controller tests

**what will I do this week?**
- Finish up Controller tests
- Bug fixes for displaying content on Project page

**what is holding me back? (optional)**
- N/A
